/*
@author Keith Ginoel S. Gabinete
@date 2024-04-21 13:18:05
*/
/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.
*/

/**
 * @param {string} s
 * @param {string} t
 * @return {character}
 */
var findTheDifference = function(s, t) {
    let addedCharacter = ''; // will store the added character

    // sort the strings
    s = s.split('').sort().join('');
    t = t.split('').sort().join('');

    // iterate through the strings
    for (let i=0; i<t.length; i++) {
        // if the current character in t is not equal to the current character in s, then it is the added character
        if (t[i]!=s[i]) {
            addedCharacter += t[i];
            break; // exit the loop
        }
    }
    
    // return the added character
    return addedCharacter;
};

// sample run
// expected output: 'e'
const sampleS1 = "abcd";
const sampleT1 = "abcde"; 

// expacted output: 'y'
const sampleS2 = "";
const sampleT2 = "y"; 

console.log(findTheDifference(sampleS1, sampleT1));
console.log(findTheDifference(sampleS2, sampleT2));